#automatically generated by the FlatBuffers compiler, do not modify

#namespace : Messages

import flatbuffers from flatbuffers.compat import import_numpy np = import_numpy()

    class Point(object) : __slots__ =['_tab']

#Point
    def Init(self, buf, pos) : self._tab = flatbuffers.table.Table(buf, pos)

#Point
                                                                       def X(self) : return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
#Point
                                                                                                                                                   def Y(self) : return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

                                                                                                                                                                                                                               def CreatePoint(builder, x, y) : builder.Prep(4, 8) builder.PrependInt32(y) builder.PrependInt32(x) return builder.Offset()
